export { default as Home } from './Home/Home'
export { default as Search } from './Search/Search'
export { default as NotFound } from './NotFound/NotFound'
export { default as Page } from './Page/Page'
export { default as Error } from './Error/Error'
